### ISSUE TITLE
Corner case system error 

### ISSUE THREAD

**Issue by thejeshgn** [dshanske/simple-location#187]
I posted using Android app. I think there was some issue and some attributes of `geo_` was not set. So the site started throwing the following error.

It worked well, after I disabled the plugin, edited the post removed geo things and reactivated the plugin. May be a check is required.

```
WordPress version 5.4.2
Current plugin: Simple Location (version 4.1.8)
PHP version 7.3.12



Error Details
=============
An error of type E_ERROR was caused in line 204 of the file /var/www/wp-content/plugins/simple-location/includes/class-loc-view.php. Error message: Uncaught Error: Call to a member function set() on null in /var/www/wp-content/plugins/simple-location/includes/class-loc-view.php:204
Stack trace:
#0 /var/www/wp-content/plugins/simple-location/includes/class-loc-view.php(363): Loc_View::get_map()
#1 /var/www/wp-includes/class-wp-hook.php(287): Loc_View::content_map('\n

```

**Comment by dshanske** [comment]
This should be resolved.
