### ISSUE TITLE
jsonfeed plugin crashing with simple location

### ISSUE THREAD

**Issue by deverman** [dshanske/simple-location#71]
Hi, I guess after updating to the lastest version of simple location, my jsonfeed stopped working. when checking the error logs it seems that the problem was related to simple location. Indeed after disabling the simple location plugin the feed is again working. Let me know if you need me to provide anymore details. 

```
[26-May-2018 01:03:00 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Geo_Data::json_feed_item(), 1 passed in /home/example/example/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in /home/example/example/wp-content/plugins/simple-location/includes/class-geo-data.php:124
Stack trace:
#0 /home/example/example/wp-includes/class-wp-hook.php(288): WP_Geo_Data::json_feed_item(Array)
#1 /home/example/example/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /home/example/example/wp-content/plugins/jsonfeed/feed-template.php(56): apply_filters('json_feed_item', Array, Object(WP_Post))
#3 /home/example/example/wp-includes/template.php(688): require_once('/home/wikishen/...')
#4 /home/example/example/wp-content/plugins/jsonfeed/jsonfeed-wp.php(27): load_template('/home/wikishen/...')
#5 /home/example/example/wp-includes/class-wp-hook.php(286): json_feed_render_feed(false, 'json')
#6 /home/example/example/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) in /home/example/example/wp-content/plugins/simple-location/includes/class-geo-data.php on line 124

```

**Comment by dshanske** [comment]
Would you try the Github master version and advise if it addresses before I push this to wordpress.org?

**Comment by deverman** [comment]
Sorry I missed this message however just saw that you pushed it to wordpress.org and I tested it and it is now working. Really appreciate the fast response.
